"""
This type stub file was generated by pyright.
"""

from .interaction import *
from .message_components import *

__all__ = ("MessageInteraction", "ButtonInteraction")

class PartialTextChannel:
    def __init__(self, channel_id) -> None: ...

class MessageInteraction(BaseInteraction):
    """
    Represents a button interaction.
    Obtainable via :class:`discord.Context.wait_for_button_click`
    and in ``on_button_click`` event.

    Attributes
    ----------
    author : :class:`discord.Member` | :class:`discord.User`
        The user that clicked the button
    channel : :class:`discord.Messageable`
        The channel where the click happened
    guild : :class:`discord.Guild` | ``None``
        The guild where the click happened
    message : :class:`discord.Message`
        The message where the button was clicked
    components : :class:`list`
        A list of :class:`ActionRow` instances containing other components
    component : :class:`Component`
        The component that author interacted with
    """

    def __init__(self, client, data) -> None: ...
    @property
    def clicked_button(self) -> Button: ...
    @property
    def button(self) -> Button: ...
    @property
    def select_menu(self) -> SelectMenu: ...

ButtonInteraction = MessageInteraction
