"""
This type stub file was generated by pyright.
"""

from discord import DiscordException

class SlashCommandError(DiscordException):
    """
    The base exception type for all slash-command related errors.

    This inherits from :exc:`discord.DiscordException`.

    This exception and exceptions inherited from it are handled
    in a special way as they are caught and passed into a special event
    from :class:`.SlashClient`, :func:`on_slash_command_error`.
    """

    def __init__(self, message=..., *args) -> None: ...

class BadArgument(SlashCommandError): ...
class SlashCheckFailure(SlashCommandError): ...

class CheckAnyFailure(SlashCheckFailure):
    def __init__(self, checks, errors) -> None: ...

class PrivateMessageOnly(SlashCheckFailure):
    def __init__(self, message=...) -> None: ...

class NoPrivateMessage(SlashCheckFailure):
    def __init__(self, message=...) -> None: ...

class NotOwner(SlashCheckFailure): ...

class CommandOnCooldown(SlashCommandError):
    """Exception raised when the slash-command being invoked is on cooldown.

    This inherits from `SlashCommandError`

    ## Attributes

    `cooldown`: `Cooldown` (a class with attributes `rate`, `per`, and `type`)

    `retry_after`: `float` (the amount of seconds to wait before you can retry again)
    """

    def __init__(self, cooldown, retry_after) -> None: ...

class NotGuildOwner(SlashCommandError): ...

class MissingRole(SlashCheckFailure):
    def __init__(self, missing_role) -> None: ...

class BotMissingRole(SlashCheckFailure):
    def __init__(self, missing_role) -> None: ...

class MissingAnyRole(SlashCheckFailure):
    def __init__(self, missing_roles) -> None: ...

class BotMissingAnyRole(SlashCheckFailure):
    def __init__(self, missing_roles) -> None: ...

class NSFWChannelRequired(SlashCheckFailure):
    def __init__(self, channel) -> None: ...

class MissingPermissions(SlashCheckFailure):
    def __init__(self, missing_perms, *args) -> None: ...

class BotMissingPermissions(SlashCheckFailure):
    def __init__(self, missing_perms, *args) -> None: ...
