"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict

from .slash_command import SlashCommand, SlashCommandPermissions

__all__ = ("SlashClient",)

class SlashClient:
    """
    The main purpose of this class is to track ``INTERACTION_CREATE`` API event.

    Parameters
    ----------
    client : :class:`commands.Bot` | :class:`commands.AutoShardedBot`
        The discord.py Bot instance
    show_warnings : :class:`bool`
        Whether to show the warnings or not. Defaults to ``True``
    modify_send : :class:`bool`
        Whether to modify :class:`Messageable.send` and :class:`Message.edit`.
        Modified methods allow to specify the ``components`` parameter.

    Attributes
    ----------
    client : :class:`commands.Bot` | :class:`commands.AutoShardedBot`
    global_commands : :class:`list`
        All registered global commands are cached here
    commands : :class:`list`
        All working slash commands
    is_ready : bool
        Equals to ``True`` if SlashClient is ready, otherwise it's ``False``
    """

    def __init__(self, client, *, show_warnings: bool = ..., modify_send: bool = ...) -> None: ...
    def teardown(self):  # -> None:
        """Cleanup the client by removing all registered listeners and caches."""
        ...
    @property
    def commands(self): ...
    @property
    def global_commands(self): ...
    def event(self, func):
        """
        Decorator
        ::

            @slash.event
            async def on_ready():
                print("SlashClient is ready")

        | All possible events:
        | ``on_ready``, ``on_auto_register``,
        | ``on_slash_command``, ``on_slash_command_error``
        """
        ...
    def command(self, *args, **kwargs):  # -> (func: Unknown) -> CommandParent:
        """
        A decorator that allows to build a slash command.

        Parameters
        ----------
        auto_sync : :class:`bool`
            whether to automatically register the command or not. Defaults to ``True``
        name : :class:`str`
            name of the slash command you want to respond to (equals to function name by default).
        description : :class:`str`
            the description of the slash command. It will be visible in Discord.
        options : :class:`List[Option]`
            the list of slash command options. The options will be visible in Discord.
        default_permission : :class:`bool`
            whether the command is enabled by default when the app is added to a guild.
        guild_ids : :class:`List[int]`
            if specified, the client will register a command in these guilds.
            Otherwise this command will be registered globally.
        connectors : :class:`dict`
            which function param states for each option. If the name
            of an option already matches the corresponding function param,
            you don't have to specify the connectors. Connectors template:
            ``{"option-name": "param_name", ...}``
        """
        ...
    def get_global_command(self, command_id: int):  # -> SlashCommand | None:
        """
        Get a cached global command

        Parameters
        ----------

        command_id : int
            the ID of the command

        Returns
        -------

        slash_command : SlashCommand | None
        """
        ...
    def get_global_command_named(self, name: str):  # -> SlashCommand | None:
        """
        Get a cached global command matching the specified name

        Parameters
        ----------

        name : str
            the name of the command

        Returns
        -------

        slash_command : SlashCommand | None
        """
        ...
    def get_guild_command(self, guild_id: int, command_id: int):  # -> None:
        """
        Get a cached guild command

        Parameters
        ----------

        guild_id : int
            the ID of the guild

        command_id : int
            the ID of the command

        Returns
        -------

        slash_command : SlashCommand | None
        """
        ...
    def get_guild_command_named(self, guild_id: int, name: str):  # -> None:
        """
        Get a cached guild command matching the specified name

        Parameters
        ----------

        guild_id : int
            the ID of the guild

        name : str
            the name of the command

        Returns
        -------

        slash_command : SlashCommand | None
        """
        ...
    def get_guild_commands(self, guild_id: int):  # -> list[Unknown | Any]:
        """
        Get cached guild commands

        Parameters
        ----------

        guild_id : int
            the ID of the guild

        Returns
        -------

        slash_commands : List[SlashCommand]
        """
        ...
    async def fetch_global_commands(self):  # -> list[SlashCommand]:
        """
        Requests a list of global registered commands from the API

        Returns
        -------

        global_commands : List[SlashCommand]
        """
        ...
    async def fetch_guild_commands(self, guild_id: int):  # -> list[SlashCommand]:
        """
        Requests a list of registered commands for a specific guild

        Parameters
        ----------

        guild_id : int

        Returns
        -------

        guild_commands : List[SlashCommand]
        """
        ...
    async def fetch_global_command(self, command_id: int):  # -> SlashCommand:
        """
        Requests a registered global slash-command

        Parameters
        ----------

        command_id : int

        Returns
        -------

        global_command : SlashCommand
        """
        ...
    async def fetch_guild_command(self, guild_id: int, command_id: int):  # -> SlashCommand:
        """
        Requests a registered guild command

        Parameters
        ----------

        guild_id : int

        command_id : int

        Returns
        -------

        guild_command : SlashCommand
        """
        ...
    async def register_global_slash_command(self, slash_command: SlashCommand):  # -> SlashCommand:
        """
        Registers a global slash-command

        .. seealso:: :ref:`raw_slash_command`

        Parameters
        ----------

        slash_command : SlashCommand
        """
        ...
    async def register_guild_slash_command(
        self, guild_id: int, slash_command: SlashCommand
    ):  # -> SlashCommand:
        """
        Registers a local slash-command

        .. seealso:: :ref:`raw_slash_command`

        Parameters
        ----------

        guild_id : int

        slash_command : SlashCommand
        """
        ...
    async def overwrite_global_commands(self, slash_commands: list):  # -> list[SlashCommand]:
        """
        Bulk overwrites all global commands

        Parameters
        ----------

        slash_commands : List[SlashCommand]
        """
        ...
    async def overwrite_guild_commands(self, guild_id: int, slash_commands: list):  # -> None:
        """
        Bulk overwrites all guild commands

        Parameters
        ----------

        guild_id : int

        slash_commands : List[SlashCommand]
        """
        ...
    async def edit_global_slash_command(
        self, command_id: int, slash_command: SlashCommand, **kwargs
    ):  # -> SlashCommand:
        """
        Edits a global command

        Parameters
        ----------
        command_id : int
        slash_command : SlashCommand
            replacement of the old data
        """
        ...
    async def edit_guild_slash_command(
        self, guild_id: int, command_id: int, slash_command: SlashCommand, **kwargs
    ):  # -> SlashCommand:
        """
        Edits a local command

        Parameters
        ----------
        guild_id : int
        command_id : int
        slash_command : SlashCommand
            replacement of the old data
        """
        ...
    async def delete_global_slash_command(self, command_id: int):  # -> None:
        """
        Deletes a global command

        Parameters
        ----------

        command_id : int
        """
        ...
    async def delete_guild_slash_command(self, guild_id: int, command_id: int):  # -> None:
        """
        Deletes a local command

        Parameters
        ----------

        guild_id : int

        command_id : int
        """
        ...
    async def delete_global_commands(self):  # -> None:
        """
        Deletes all global commands.
        """
        ...
    async def delete_guild_commands(self, guild_id: int):  # -> None:
        """
        Deletes all local commands in the specified guild.

        Parameters
        ----------
        guild_id : int
            the ID of the guild where you're going to delete the commands
        """
        ...
    async def fetch_guild_command_permissions(
        self, guild_id: int, command_id: int
    ):  # -> SlashCommandPermissions:
        """
        Fetches command permissions for a specific command in a guild.

        Parameters
        ----------
        guild_id : :class:`int`
            the ID of the guild
        command_id : :class:`int`
            the ID of the command
        """
        ...
    async def batch_fetch_guild_command_permissions(
        self, guild_id: int
    ):  # -> dict[int, SlashCommandPermissions]:
        """
        Fetches command permissions for all commands in a guild.

        Parameters
        ----------
        guild_id : :class:`int`
            the ID of the guild
        """
        ...
    async def edit_guild_command_permissions(
        self, guild_id: int, command_id: int, permissions: SlashCommandPermissions
    ):  # -> None:
        """
        Edits command permissions for a specific command in a guild.

        Parameters
        ----------
        guild_id : :class:`int`
            the ID of the guild
        command_id : :class:`int`
            the ID of the command
        permissions : :class:`SlashCommandPermissions` | :class:`dict`
            new permissions to set. If you use :class:`SlashCommandPermissions.from_pairs`,
            you can pass the arg of that method straight into this function
        """
        ...
    async def batch_edit_guild_command_permissions(
        self, guild_id: int, permissions: dict
    ):  # -> None:
        """
        Batch edits permissions for all commands in a guild.

        Parameters
        ----------
        guild_id : :class:`int`
            the ID of the guild
        permissions : :class:`dict`
            a dictionary of ``command_id``: :class:`SlashCommandPermissions`
        """
        ...
    async def fetch_global_command_named(self, name: str):  # -> SlashCommand | None:
        """
        Fetches a global command that matches the specified name

        Parameters
        ----------

        name : str
            the name of the command to fetch
        """
        ...
    async def fetch_guild_command_named(self, guild_id: int, name: str):  # -> SlashCommand | None:
        """
        Fetches a guild command that matches the specified name

        Parameters
        ----------

        guild_id : int
            ID of the guild where the command is registered

        name : str
            the name of the command to fetch
        """
        ...
    async def edit_global_command_named(self, name: str, slash_command: SlashCommand):  # -> None:
        """
        Edits a global command matching the specified name.

        Parameters
        ----------

        name : str
            the name of the command to edit

        slash_command : SlashCommand
            replacement of the old data
        """
        ...
    async def edit_guild_command_named(
        self, guild_id: int, name: str, slash_command: SlashCommand
    ):  # -> None:
        """
        Edits a local command matching the specified name.

        Parameters
        ----------

        guild_id : int
            ID of the guild where the command is registered

        name : str
            the name of the command to edit

        slash_command : SlashCommand
            replacement of the old data
        """
        ...
    async def delete_global_command_named(self, name: str):  # -> None:
        """
        Deletes a global command matching the specified name.

        Parameters
        ----------

        name : str
            the name of the command to delete
        """
        ...
    async def delete_guild_command_named(self, guild_id: int, name: str):  # -> None:
        """
        Deletes a local command matching the specified name.

        Parameters
        ----------

        guild_id : int
            ID of the guild where the command is registered

        name : str
            the name of the command to edit
        """
        ...
    def dispatch(self, event_name, *args, **kwargs): ...
    async def wait_for_button_click(self, check=..., timeout=...): ...
    async def wait_for_dropdown(self, check=..., timeout=...): ...
    async def multiple_wait_for(
        self, events_and_checks: Dict[str, Any], timeout: float = ...
    ):  # -> None:
        """
        Waits until one of the given events toggles and matches the relevant check.

        Example:

        ::

            result = None
            try:
                result = await client.multiple_wait_for(
                    {
                        "message": lambda msg: msg.author == ctx.author,
                        "reaction_add": lambda react, user: user == ctx.author
                    },
                    timeout=60
                )
            except asyncio.TimeoutError:
                await ctx.send("It took too long")
            if isinstance(result, discord.Message):
                # on_message was toggled
                await ctx.send(f"You said '{result.content}'")
            else:
                # on_reaction_add was toggled
                reaction, user = result
                await ctx.send(f"Your reaction: {reaction.emoji}")

        Parameters
        ----------
        events_and_checks : Dict[:class:`str`, :class:`function | None`]
            a dictionary of event names and relevant checks, e.g.
            ``{"message": lambda m: m.author == ctx.author, "button_click": None}``
        timeout : :class:`float` | :class:`None`
            the amount of seconds the bot should wait for any of the given events
        """
        ...
    register_global_command = ...
    register_guild_command = ...
    edit_global_command = ...
    edit_guild_command = ...
    delete_global_command = ...
    delete_guild_command = ...
