"""
This type stub file was generated by pyright.
"""

from .errors import *

__all__ = (
    "BucketType",
    "InvokableApplicationCommand",
    "check",
    "check_any",
    "has_role",
    "has_any_role",
    "bot_has_role",
    "bot_has_any_role",
    "has_permissions",
    "bot_has_permissions",
    "has_guild_permissions",
    "bot_has_guild_permissions",
    "dm_only",
    "guild_only",
    "is_owner",
    "is_nsfw",
    "cooldown",
)

class InvokableApplicationCommand:
    def __init__(self, func, *, name=..., **kwargs) -> None: ...
    async def __call__(self, *args, **kwargs): ...
    def error(self, func):
        """
        A decorator that makes the function below
        work as error handler for this command.
        """
        ...
    def is_on_cooldown(self, inter):  # -> bool:
        """
        Checks whether the slash command is currently on cooldown.

        Parameters
        -----------
        inter: :class:`SlashInteraction`
            The interaction to use when checking the commands cooldown status.

        Returns
        --------
        :class:`bool`
            A boolean indicating if the slash command is on cooldown.
        """
        ...
    def reset_cooldown(self, inter):  # -> None:
        """
        Resets the cooldown on this slash command.

        Parameters
        -----------
        inter: :class:`SlashInteraction`
            The interaction to reset the cooldown under.
        """
        ...
    def get_cooldown_retry_after(self, inter):  # -> float:
        """
        Retrieves the amount of seconds before this slash command can be tried again.

        Parameters
        -----------
        inter: :class:`SlashInteraction`
            The interaction to retrieve the cooldown from.

        Returns
        --------
        :class:`float`
            The amount of time left on this slash command's cooldown in seconds.
            If this is ``0.0`` then the slash command isn't on cooldown.
        """
        ...

def class_name(func): ...
def get_class(func): ...
def check(predicate):  # -> (func: Unknown) -> (InvokableApplicationCommand | Unknown):
    """
    A function that converts ``predicate(interaction)`` functions
    into application command decorators

    Example

    ::

        def is_guild_owner():
            def predicate(inter):
                return inter.author.id == inter.guild.owner_id
            return check(predicate)

        @is_guild_owner()
        @slash.command(description="Says Hello if you own the guild")
        async def hello(inter):
            await inter.reply("Hello, Mr.Owner!")

    """
    ...

def check_any(*checks):  # -> (func: Unknown) -> (InvokableApplicationCommand | Unknown):
    """Similar to ``commands.check_any``"""
    ...

def has_role(item):  # -> (func: Unknown) -> (InvokableApplicationCommand | Unknown):
    """Similar to ``commands.has_role``"""
    ...

def has_any_role(*items):  # -> (func: Unknown) -> (InvokableApplicationCommand | Unknown):
    """Similar to ``commands.has_any_role``"""
    ...

def bot_has_role(item):  # -> (func: Unknown) -> (InvokableApplicationCommand | Unknown):
    """Similar to ``commands.bot_has_role``"""
    ...

def bot_has_any_role(*items):  # -> (func: Unknown) -> (InvokableApplicationCommand | Unknown):
    """Similar to ``commands.bot_has_any_role``"""
    ...

def has_permissions(**perms):  # -> (func: Unknown) -> (InvokableApplicationCommand | Unknown):
    """Similar to ``commands.has_permissions``"""
    ...

def bot_has_permissions(**perms):  # -> (func: Unknown) -> (InvokableApplicationCommand | Unknown):
    """Similar to ``commands.bot_has_permissions``"""
    ...

def has_guild_permissions(
    **perms,
):  # -> (func: Unknown) -> (InvokableApplicationCommand | Unknown):
    """Similar to ``commands.has_guild_permissions``"""
    ...

def bot_has_guild_permissions(
    **perms,
):  # -> (func: Unknown) -> (InvokableApplicationCommand | Unknown):
    """Similar to ``commands.bot_has_guild_permissions``"""
    ...

def dm_only():  # -> (func: Unknown) -> (InvokableApplicationCommand | Unknown):
    """Similar to ``commands.dm_only``"""
    ...

def guild_only():  # -> (func: Unknown) -> (InvokableApplicationCommand | Unknown):
    """Similar to ``commands.guild_only``"""
    ...

def is_owner():  # -> (func: Unknown) -> (InvokableApplicationCommand | Unknown):
    """Similar to ``commands.is_owner``"""
    ...

def is_nsfw():  # -> (func: Unknown) -> (InvokableApplicationCommand | Unknown):
    """Similar to ``commands.is_nsfw``"""
    ...

def cooldown(
    rate, per, type=...
):  # -> (func: Unknown) -> (InvokableApplicationCommand | Unknown):
    """
    A decorator that adds a cooldown to a slash-command. Similar to **discord.py** cooldown decorator.

    A cooldown allows a command to only be used a specific amount
    of times in a specific time frame. These cooldowns can be based
    either on a per-guild, per-channel, per-user, per-role or global basis.
    Denoted by the third argument of ``type`` which must be of enum
    type ``BucketType``.

    If a cooldown is triggered, then ``CommandOnCooldown`` is triggered in
    ``on_slash_command_error`` in the local error handler.

    A command can only have a single cooldown.

    Parameters
    ----------
    rate : int
        The number of times a command can be used before triggering a cooldown.
    per : float
        The amount of seconds to wait for a cooldown when it's been triggered.
    type : BucketType
        The type of cooldown to have.
    """
    ...
