from typing import List

BROADCAST_IP: str
DEFAULT_PORT: int

def create_magic_packet(macaddress: str) -> bytes: ...
def send_magic_packet(*macs: str, ip_address: str = ..., port: int = ...) -> None: ...
def main(argv: List[str] = ...) -> None: ...
