from typing import Any, Optional

from matplotlib.axes._base import _AxesBase

class SecondaryAxis(_AxesBase):
    def __init__(
        self, parent: Any, orientation: Any, location: Any, functions: Any, **kwargs: Any
    ) -> None: ...
    def set_alignment(self, align: Any) -> None: ...
    def set_location(self, location: Any) -> None: ...
    def apply_aspect(self, position: Optional[Any] = ...) -> None: ...
    stale: bool = ...
    def set_ticks(self, ticks: Any, *, minor: bool = ...): ...
    def set_functions(self, functions: Any): ...
    def draw(self, *args: Any, **kwargs: Any) -> None: ...
    def set_aspect(self, *args: Any, **kwargs: Any) -> None: ...
    def set_color(self, color: Any) -> None: ...
