from typing import Any, Optional

from matplotlib import docstring as docstring  # type:ignore
from matplotlib.axes._axes import Axes as Axes
from matplotlib.gridspec import GridSpec as GridSpec
from matplotlib.gridspec import SubplotSpec as SubplotSpec

class SubplotBase:
    def __init__(self, fig: Any, *args: Any, **kwargs: Any) -> None: ...
    def __reduce__(self): ...
    def get_geometry(self): ...
    def change_geometry(self, numrows: Any, numcols: Any, num: Any) -> None: ...
    def get_subplotspec(self): ...
    def set_subplotspec(self, subplotspec: Any) -> None: ...
    def get_gridspec(self): ...
    @property
    def figbox(self): ...
    @property
    def numRows(self): ...
    @property
    def numCols(self): ...
    def update_params(self) -> None: ...
    def is_first_row(self): ...
    def is_last_row(self): ...
    def is_first_col(self): ...
    def is_last_col(self): ...
    def label_outer(self) -> None: ...

def subplot_class_factory(axes_class: Optional[Any] = ...): ...

Subplot: Any
