from typing import Any, Optional

from dateutil.relativedelta import relativedelta as relativedelta
from dateutil.rrule import DAILY as DAILY
from dateutil.rrule import FR as FR
from dateutil.rrule import HOURLY as HOURLY
from dateutil.rrule import MINUTELY as MINUTELY
from dateutil.rrule import MO as MO
from dateutil.rrule import MONTHLY as MONTHLY
from dateutil.rrule import SA as SA
from dateutil.rrule import SECONDLY as SECONDLY
from dateutil.rrule import SU as SU
from dateutil.rrule import TH as TH
from dateutil.rrule import TU as TU
from dateutil.rrule import WE as WE
from dateutil.rrule import WEEKLY as WEEKLY
from dateutil.rrule import YEARLY as YEARLY
from dateutil.rrule import rrule as rrule
from matplotlib import ticker, units  # type:ignore

MICROSECONDLY: Any

def set_epoch(epoch: Any) -> None: ...
def get_epoch(): ...
def datestr2num(d: Any, default: Optional[Any] = ...): ...
def date2num(d: Any): ...
def num2date(x: Any, tz: Optional[Any] = ...): ...
def num2timedelta(x: Any): ...
def drange(dstart: Any, dend: Any, delta: Any): ...

class DateFormatter(ticker.Formatter):
    @property
    def illegal_s(self): ...
    fmt: Any = ...
    tz: Any = ...
    def __init__(
        self, fmt: Any, tz: Optional[Any] = ..., *, usetex: Optional[Any] = ...
    ) -> None: ...
    def __call__(self, x: Any, pos: int = ...): ...
    def set_tzinfo(self, tz: Any) -> None: ...

class IndexDateFormatter(ticker.Formatter):
    t: Any = ...
    fmt: Any = ...
    tz: Any = ...
    def __init__(self, t: Any, fmt: Any, tz: Optional[Any] = ...) -> None: ...
    def __call__(self, x: Any, pos: int = ...): ...

class ConciseDateFormatter(ticker.Formatter):
    defaultfmt: str = ...
    formats: Any = ...
    zero_formats: Any = ...
    offset_formats: Any = ...
    offset_string: str = ...
    show_offset: Any = ...
    def __init__(
        self,
        locator: Any,
        tz: Optional[Any] = ...,
        formats: Optional[Any] = ...,
        offset_formats: Optional[Any] = ...,
        zero_formats: Optional[Any] = ...,
        show_offset: bool = ...,
        *,
        usetex: Optional[Any] = ...,
    ) -> None: ...
    def __call__(self, x: Any, pos: Optional[Any] = ...): ...
    def format_ticks(self, values: Any): ...
    def get_offset(self): ...
    def format_data_short(self, value: Any): ...

class AutoDateFormatter(ticker.Formatter):
    defaultfmt: Any = ...
    scaled: Any = ...
    def __init__(
        self,
        locator: Any,
        tz: Optional[Any] = ...,
        defaultfmt: str = ...,
        *,
        usetex: Optional[Any] = ...,
    ) -> None: ...
    def __call__(self, x: Any, pos: Optional[Any] = ...): ...

class rrulewrapper:
    def __init__(self, freq: Any, tzinfo: Optional[Any] = ..., **kwargs: Any) -> None: ...
    def set(self, **kwargs: Any) -> None: ...
    def __getattr__(self, name: Any): ...

class DateLocator(ticker.Locator):
    hms0d: Any = ...
    tz: Any = ...
    def __init__(self, tz: Optional[Any] = ...) -> None: ...
    def set_tzinfo(self, tz: Any) -> None: ...
    def datalim_to_dt(self): ...
    def viewlim_to_dt(self): ...
    def nonsingular(self, vmin: Any, vmax: Any): ...

class RRuleLocator(DateLocator):
    rule: Any = ...
    def __init__(self, o: Any, tz: Optional[Any] = ...) -> None: ...
    def __call__(self): ...
    def tick_values(self, vmin: Any, vmax: Any): ...
    @staticmethod
    def get_unit_generic(freq: Any): ...

class AutoDateLocator(DateLocator):
    minticks: Any = ...
    maxticks: Any = ...
    interval_multiples: Any = ...
    intervald: Any = ...
    def __init__(
        self,
        tz: Optional[Any] = ...,
        minticks: int = ...,
        maxticks: Optional[Any] = ...,
        interval_multiples: bool = ...,
    ) -> None: ...
    def __call__(self): ...
    def tick_values(self, vmin: Any, vmax: Any): ...
    def nonsingular(self, vmin: Any, vmax: Any): ...
    def get_locator(self, dmin: Any, dmax: Any): ...

class YearLocator(DateLocator):
    base: Any = ...
    replaced: Any = ...
    def __init__(
        self, base: int = ..., month: int = ..., day: int = ..., tz: Optional[Any] = ...
    ) -> None: ...
    def __call__(self): ...
    def tick_values(self, vmin: Any, vmax: Any): ...

class MonthLocator(RRuleLocator):
    def __init__(
        self,
        bymonth: Optional[Any] = ...,
        bymonthday: int = ...,
        interval: int = ...,
        tz: Optional[Any] = ...,
    ) -> None: ...

class WeekdayLocator(RRuleLocator):
    def __init__(
        self, byweekday: int = ..., interval: int = ..., tz: Optional[Any] = ...
    ) -> None: ...

class DayLocator(RRuleLocator):
    def __init__(
        self, bymonthday: Optional[Any] = ..., interval: int = ..., tz: Optional[Any] = ...
    ) -> None: ...

class HourLocator(RRuleLocator):
    def __init__(
        self, byhour: Optional[Any] = ..., interval: int = ..., tz: Optional[Any] = ...
    ) -> None: ...

class MinuteLocator(RRuleLocator):
    def __init__(
        self, byminute: Optional[Any] = ..., interval: int = ..., tz: Optional[Any] = ...
    ) -> None: ...

class SecondLocator(RRuleLocator):
    def __init__(
        self, bysecond: Optional[Any] = ..., interval: int = ..., tz: Optional[Any] = ...
    ) -> None: ...

class MicrosecondLocator(DateLocator):
    tz: Any = ...
    def __init__(self, interval: int = ..., tz: Optional[Any] = ...) -> None: ...
    def set_axis(self, axis: Any): ...
    def set_view_interval(self, vmin: Any, vmax: Any): ...
    def set_data_interval(self, vmin: Any, vmax: Any): ...
    def __call__(self): ...
    def tick_values(self, vmin: Any, vmax: Any): ...

def epoch2num(e: Any): ...
def num2epoch(d: Any): ...

class DateConverter(units.ConversionInterface):
    def __init__(self, *, interval_multiples: bool = ...) -> None: ...
    def axisinfo(self, unit: Any, axis: Any): ...
    @staticmethod
    def convert(value: Any, unit: Any, axis: Any): ...
    @staticmethod
    def default_units(x: Any, axis: Any): ...

class ConciseDateConverter(DateConverter):
    def __init__(
        self,
        formats: Optional[Any] = ...,
        zero_formats: Optional[Any] = ...,
        offset_formats: Optional[Any] = ...,
        show_offset: bool = ...,
        *,
        interval_multiples: bool = ...,
    ) -> None: ...
    def axisinfo(self, unit: Any, axis: Any): ...

class _rcParam_helper:
    conv_st: str = ...
    int_mult: bool = ...
    @classmethod
    def set_converter(cls, s: Any) -> None: ...
    @classmethod
    def set_int_mult(cls, b: Any) -> None: ...
    @classmethod
    def register_converters(cls) -> None: ...
