name: Cog release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    name: Release
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install gitpython requests

      - name: Set up git
        run: |
          git config user.name "actions-user"
          git config user.email ""

      - name: Run script release.py
        run: |
          python .github/workflows/scripts/release.py
        env:
          CF_KV: ${{ secrets.CF_KV }}
